name: Build/Release
on: [push, pull_request]

permissions:
  contents: write

env:
  NeosPath: "${{ github.workspace }}/neos_install/" #see neos-modding-group/neos-plugin-setup-action
  BUILD_TYPE: "CICD"
  PUBLISH_ARTIFACTS: ${{ startsWith(github.ref, 'refs/tags/') || contains(github.ref, 'publish-test') }}
  UPLOAD_ARTIFACTS: ${{ startsWith(github.ref, 'refs/tags/') || contains(github.ref, 'publish-test') || github.ref == 'refs/heads/main' || contains(github.ref, 'upload-test') }} # only publish workflow artifacts for pushes to main or tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
        #TODO: check for possible caching of neos build env
      - name: Download NeosModLoader and Harmony
        run: |
          mkdir -p "${NeosPath}/nml_libs" "${NeosPath}/Libraries"
          cd "${NeosPath}/nml_libs" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/0Harmony.dll"
          cd "${NeosPath}/Libraries" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/NeosModLoader.dll"
      - name: Lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosAssetImportHook.sln
      - name: Build binaries, create release directory structure
        run: |
          dotnet build ./NeosAssetImportHook.sln --configuration Release

          mkdir ./release
          
          mv ./NeosAssetImportHook/bin/Release/net462/win-x64/NeosAssetImportHook.dll ./release/NeosAssetImportHook.dll

      - name: Run tests
        run: dotnet test ./NeosAssetImportHook.sln

      - name: Calculate SHA256
        run: sha256sum ./release/*.dll

      - name: Upload artifacts (NeosAssetImportHook.dll)
        if: ${{ env.UPLOAD_ARTIFACTS == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: NeosAssetImportHook.dll
          path: ./release/NeosAssetImportHook.dll
          if-no-files-found: error
          
      - name: Create release draft
        if: ${{ env.PUBLISH_ARTIFACTS == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/*.dll
          draft: true
